bitbook/apps/crud/models.py
from datetime import datetime

from apps.app import db ,login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model,UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String, index = True)
    email = db.Column(db.String,unique=True,index = True)
    address = db.Column(db.String,index = True)
    password_hash = db.Column(db.String)
    gar = db.Column(db.Integer,index = True)
    oni = db.Column(db.Integer,index = True)
    car = db.Column(db.Integer,index = True)
    created_at = db.Column(db.DateTime,default = datetime.now)
    updated_at = db.Column(db.DateTime, default = datetime.now, onupdate = datetime.now)

    @property
    def password(self):
        raise AttributeError("읽어 들일수 없음")
    
    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)
    
    def is_duplicate_email(self):
        return User.query.filter_by(email = self.email).first() is not None
    
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

bitbook/apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField,StringField,SubmitField,IntegerField
from wtforms.validators import DataRequired, Email, Length

class UserForm(FlaskForm):
    username = StringField(
        "사용자명",
        validators=[
            DataRequired(message="사용자 명은 필수입니다."),
            Length(max=30,message="30자 이내로 입력해 주세요"),
        ],
    )

    email = StringField(
        "메일주소",
        validators=[
            DataRequired(message="메일주소는 필수입니다."),
            Email(message="메일 주소의 형식으로 입력해 주세요."),
        ],
    )

    password = PasswordField(
        "비밀번호",
        validators=[DataRequired(message="비밀번호는 필수입니다.")]
    )
    address = StringField(
        "주소지",
        validators=[
            DataRequired(message="주소지는 필수입니다.")
        ]
    )


    submit = SubmitField("신규 등록")
    

bitbook/apps/crud/__init__.py
import apps.crud.models

bitbook/apps/crud/views.py
from flask import Blueprint, render_template,redirect,url_for
from apps.app import db
from apps.crud.models import User
from apps.crud.forms import UserForm
from flask_login import login_required
crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static"

)

@crud.route("/")
@login_required
def index():
    return render_template("crud/index.html")

@crud.route("/sql")
@login_required
def sql():
    db.session.query(User).all()
    return "콘솔 로그를 확인해 주세요"

@crud.route("/users")
@login_required
def users():
    users = User.query.all()
    return render_template("crud/index.html",users = users)



@crud.route("/users/new",methods = ["GET","POST"])
@login_required
def create_user() :
    form = UserForm()
    if form.validate_on_submit():
        user = User(
            username = form.username.data,
            email = form.email.data,
            password = form.password.data,
            address = form.address.data,
        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    return render_template("crud/create.html", form=form)

@crud.route("/users/<user_id>",methods=["GET","POST"])
@login_required
def edit_user(user_id):
    form = UserForm()

    user = User.query.filter_by(id = user_id).first()

    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        user.address = form.address.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    return render_template("crud/edit.html",user=user, form=form)

@crud.route("/user/<user_id>/delete",methods=["POST"])
@login_required
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

bitbook/apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('crud.static',filename = 'style.css') }}"/>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

bitbook/apps/crud/templates/crud/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    {% extends "crud/base.html" %}
    {% block title %}사용자 신규 작성{% endblock %}
    {% block content %}


    <h2>사용자 신규 작성</h2>
    <form action="{{ url_for('crud.create_user') }}" method="POST" novalidate = "novalidate">
        {{form.csrf_token}}
        <p>
            {{ form.username.label }} {{ form.username (placeholder = "사용자명") }}
        </p>
        {% for error in form.username.errors %}
        <span style="color: red;"> {{ error }}</span>
        {% endfor %}

        <p>
            {{ form.email.label }}{{ form.email(placeholder="메일 주소" )}}
        </p>
        {% for error in form.email.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}

        <p>
            {{ form.password.label }} {{ form.password(placeholder="비밀번호" )}}
        </p>
        {% for error in form.password.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}

        <p>
            {{ form.address.label }}{{ form.address(placeholder="주소지")}}
        </p>
        {% for error in form.address.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}

        <p>{{ form.submit() }}</p>
    </form>

    {% endblock %}
</body>
</html>

bitbook/apps/crud/templates/crud/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>사용자 편집</title>
    <link rel="stylesheet" href="{{url_for('crud.static',filename = 'style.css')}}"/>
</head>
<body>
    {% extends "crud/base.html" %}
    {% block title %}사용자 편집{% endblock %}
    {% block content %}
    <h2>사용자 편집</h2>
    <form action="{{url_for('crud.edit_user',user_id=user.id)}}" method="POST" novalidate="novalidate">
        {{form.csrf_token}}
        <p>
            {{form.username.label}} {{form.username(placeholder="사용자명",value=username)}}
        </p>
        {% for error in form.username.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p>
            {{ form.email.label }} {{form.email(placeholder="메일 주소",value=email)}}
        </p>
        {% for error in form.email.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p>
            {{ form.password.label }} {{form.password(placeholder="비밀번호")}}
        </p>
        {% for error in form.password.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p>
            {{ form.address.labed }}{{ form.address(placeholder="집주소")}}
        </p>
        {% for error in form.address.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}


        <p><input type="submit" value="갱신"></p>

    </form>
    <form action="{{ url_for('crud.delete_user',user_id=user.id) }}" method="POST">
        {{form.csrf_token}}
        <input type="submit" value="삭제">
    </form>
    {% endblock %}
</body>
</html>

bitbook/apps/crud/templates/crud/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>사용자의 알람</title>
    <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css') }}"/>
</head>
<body>
    {% extends "crud/base.html"%}
    {% block title %}사용자의 알람{% endblock %}
    {% block content %}
    <h2>사용자의 일람</h2>

    <a href="{{url_for('crud.create_user')}}">사용자 신규 작성</a>

    <table>
        <tr>
            <th>주문자 id</th>
            <th>주문자명</th>
            <th>주소</th>
            <th>양파</th>
            <th>마늘</th>
            <th>당근</th>
            <th>총계</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>
                <a href="{{url_for('crud.edit_user', user_id = user.id)}}">{{user.id}}</a>
            </td>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.address }}</td>
            <td>{{ user.oni }}</td>
            <td>{{ user.gar }}</td>
            <td>{{ user.car }}</td>
            <td></td>
        </tr>
        {% endfor %}
    </table>
    {% endblock %}
</body>
</html>