venvs/todo_list/todo_list/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('todoapp/',include('todoapp.urls')),
    path('',view=lambda request:redirect("/todoapp/"))
]

venvs/todo_list/todoapp/urls.py
from django.urls import path,include
from . import views

app_name = 'todos'

urlpatterns = [
    path('',views.index, name='index'),
    path('<int:pk>/complete/', views.complete, name='complete'),
]

venvs/todo_list/todoapp/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50)
    modify_date = models.DateTimeField(null=True,blank=True)
    completed = models.BooleanField(default= False)

venvs/todo_list/todoapp/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ('title',)

venvs/todo_list/todoapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Todo
from .forms import TodoForm
# Create your views here.


def index(request):
    completed = request.GET.get('completed') or False
    todos = Todo.objects.filter(completed=completed)

    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.save()
    else:
        form = TodoForm()
    
    context = {
        'form': form,
        'todos': todos,
    }
    return render(request, 'todoapp/index.html', context)


def complete(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    todo.delete()
    return redirect('todos:index')

def edit(request):
    completed = request.GET.get('completed') or False
    todos = Todo.objects.filter(completed=completed)

    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.save()
    else:
        form = TodoForm(instance=todo)
    
    context = {
        'form': form,
        'todos': todos,
    }
    return render(request, 'todoapp/index.html', context)

venvs/todo_list/todoapp/templates/todoapp/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>todo 템플릿</title>
</head>
<body>
    <h1>TODOLIST</h1>

    <h1>
        {{ todo.title}}
    </h1>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <button>생성</button>
    </form>
    <hr>
      
    {% for todo in todos %}
        <h2>{{ todo.id }}번째 할일</h2>
        <p>{{ todo.title }}</p>
      
        {% if todo.completed == False %}
            <form action="{% url 'todos:complete' todo.id %}" method="POST">
                {% csrf_token %}
                <button>X</button>
            </form>
            <form action="{% url 'todos:edit' todo.id}" method="POST">
                {% csrf_token %}
                <button>수정</button>
            </form>
            <hr>
        {% endif %}
      
    {% endfor %}

</body>
</html>